project:
  type: book

book:
  title: "gelman_hill_06"
  author: "Norah Jones"
  date: "4/2/2024"
  chapters:
    - index.qmd
    - '02-basic_probability.qmd'
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



